#!/bin/sh

PROG="bdsync"
PROG_PATH="/data/app/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"


if [ -d "$PROG_PATH" ] ; then
	rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH

cp -r -v -n ./lib  $PROG_PATH/
cp -r -v -n ./bin  $PROG_PATH/
cp -r -v -n ./resource $PROG_PATH/

mkdir -p /var/lib/$PROG

chmod 777 /var/lib/$PROG
chmod 777 $PROG_PATH/bin/bdsync
chmod 777 $PROG_PATH/resource/*


if [ -f "/usr/bin/$PROG" ] ;then
	echo "$MSG_PREFIX not need add to /usr/bin"
else
	ln  -f -s $PROG_PATH/bin/$PROG /usr/bin/$PROG
fi

if [ -f "/etc/init.d/$PROG" ] ;then
	echo "$MSG_PREFIX not need add to /etc/init.d"
else
	ln  -f -s $PROG_PATH/bin/bdsync /etc/init.d/$PROG
fi

if [ -f "/etc/rc0.d/K30$PROG" ] ; then
	echo "$MSG_PREFIX not need add bdsync to boot"
else
	update-rc.d  $PROG defaults 30
fi


echo "$MSG_PREFIX install sucess $PROG"

service $PROG start
